[package]
name = "rusty_game_jam_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
gdnative = "0.10"
backtrace = "0.3"
itertools = "0.10.3"